### ISSUE TITLE
how to use templates?

### ISSUE THREAD

**Issue by nathanbraun** [chhoumann/bunnai#1]
This is awesome! Thanks for building it.  Looking at the git commits -- it looks like you most recently added the ability to use templates? Is there any documentation on how to use that?  Cheers!

**Comment by nathanbraun** [comment]
Looking at it more -- maybe the template just means using the config with `bunnai config`.  It'd be awesome to be able to use multiple templates though -- e.g. one for code + for a repository of mostly markdown/note files.

**Comment by chhoumann** [comment]
Hey @nathanbraun!

I've just added support for custom templates as well. The previous iteration was just support for editing the prompt template sent to OpenAI. Now you can define multiple templates to use :)

You can add the templates via `config`, and use them in your bunnai invocations with the `--template="name"` argument. Let me know what you think!

**Comment by nathanbraun** [comment]
Awesome, I tried it out but can't get it to work -- now when I press my shortcut (c-y) in lazygit I just see:

<img width="780" alt="image" src="https://github.com/chhoumann/bunnai/assets/3758483/d2f404b0-9374-4083-9bdd-efcd24fb767c">

I've tried configuring it a few ways. Originally (which worked with the previous version) I had:

```
customCommands:
  - key: "<c-y>" 
    description: "pick AI commit"
    command: 'git commit -m "{{.Form.Msg}}"'
    context: "files"
    prompts:
      - type: "menuFromCommand"
        title: "ai Commits"
        key: "Msg"
        command: "bunx bunnai"
        filter: '^(?P<number>\d+)\.\s(?P<message>.+)$'
        valueFormat: "{{ .message }}"
        labelFormat: "{{ .number }}: {{ .message | green }}"
```

Now that no longer works.  I tried playing around with the default + adding a custom code template with the following commands, none of which work (all showing the screenshot above):

```
command: "bunx bunnai"
command: 'bunx bunnai --template="code"'
command: 'bunx bunnai --template="default"'
command: "bunx bunnai --template=code"
```

etc.  Might just be me, let me know what you think!
